#!/usr/bin/perl -T

use strict;
use warnings;

use FindBin qw/$Bin/;
BEGIN {
  if ($Bin =~ m!([\w\./-]+)!) {
    $Bin = $1;
  } else {
    die "Bad directory $Bin\n";
  }
}
use lib "$Bin/lib";
use Jo;

my $jo = Jo->new;

print "Jo interpreter v.".$Jo::VERSION." \nHint: type 'die, quit or execute' to exit interpreter and execute program.\n";
$jo->input_loop;

print "\nBye.\n";


__END__
